#!/usr/bin/env python3
"""Inject guardrails.json into a Kiro agent config, idempotently.

Kiro has no global permission layer: deniedCommands and preToolUse hooks are
per-agent only, and the agent we use is regenerated by `aim agents update`
(its resources/mcpServers carry a versioned eventId path). So instead of
forking that agent, re-run this after an update.

    ./apply-guardrails.py                 # patch the current chat.defaultAgent
    ./apply-guardrails.py --agent NAME    # patch a named agent
    ./apply-guardrails.py --check         # report drift, change nothing

Merge is additive: deniedCommands and preToolUse are unioned, everything else
in the agent is left alone. Running twice is a no-op.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

AGENTS = Path.home() / ".kiro" / "agents"
FRAGMENT = Path(__file__).resolve().parent / "guardrails.json"


def default_agent() -> str:
    # --format json, because the plain form appends the scope: "name (global)".
    out = subprocess.run(
        ["kiro-cli", "settings", "chat.defaultAgent", "--format", "json"],
        capture_output=True, text=True, timeout=60,
    )
    try:
        name = json.loads(out.stdout.strip())
    except json.JSONDecodeError:
        name = ""
    if not isinstance(name, str) or not name:
        sys.exit("could not read chat.defaultAgent; pass --agent NAME")
    return name


def resolve(name: str) -> Path:
    exact = AGENTS / f"{name}.json"
    if exact.exists():
        return exact
    # AIM installs agents prefixed with their package, e.g.
    # StoreGenAICapabilities-nitrogen-dev-plus.json for agent nitrogen-dev-plus.
    hits = sorted(AGENTS.glob(f"*-{name}.json"))
    if len(hits) == 1:
        return hits[0]
    if not hits:
        sys.exit(f"no agent config for {name!r} under {AGENTS}")
    sys.exit(f"ambiguous: {name!r} matches {[h.name for h in hits]}")


def merge(agent: dict, fragment: dict) -> tuple[dict, list[str]]:
    """Union the fragment into the agent. Returns (agent, list of additions)."""
    added = []

    want = fragment["toolsSettings"]["shell"]["deniedCommands"]
    shell = agent.setdefault("toolsSettings", {}).setdefault("shell", {})
    have = shell.setdefault("deniedCommands", [])
    for pat in want:
        if pat not in have:
            have.append(pat)
            added.append(f"deniedCommands: {pat}")

    for hook in fragment["hooks"]["preToolUse"]:
        pre = agent.setdefault("hooks", {}).setdefault("preToolUse", [])
        if not any(h.get("command") == hook["command"] for h in pre):
            pre.append(hook)
            added.append(f"preToolUse: {hook['command']}")

    return agent, added


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--agent")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    path = resolve(args.agent or default_agent())
    agent = json.loads(path.read_text())
    _, added = merge(agent, json.loads(FRAGMENT.read_text()))

    if not added:
        print(f"{path.name}: guardrails already applied")
        return
    if args.check:
        print(f"{path.name}: MISSING {len(added)} guardrail(s)")
        for a in added:
            print(f"  - {a}")
        sys.exit(1)

    path.write_text(json.dumps(agent, indent=2) + "\n")
    print(f"{path.name}: added {len(added)} guardrail(s)")
    for a in added:
        print(f"  + {a}")


if __name__ == "__main__":
    main()
