#!/bin/bash

# Install dotfiles using bashdot

git submodule update --init --recursive
~/dotfiles/bashdot/bashdot install default

# Install dependencies

pip install --user -r requirements.txt

if [ "$1" = "mac" ]; then
    # MacOS

    # Fix copy-paste in MacOS
    brew install reattach-to-user-namespace

    # Spell checker for pylint
    brew install enchant
    # export PYENCHANT_LIBRARY_PATH=/Users/vincentqb/homebrew/lib/libenchant-2.dylib
    # pylint --disable all --enable spelling --spelling-dict en_US file.py

    brew install shellcheck

else
    # Linux
    true
fi

# Instal miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
eval "$(~/miniconda/bin/conda shell.bash hook)"
source ~/miniconda/bin/activate
conda init zsh

# Update tpm

~/.tmux/plugins/tpm/bin/update_plugins all	# prefix + U
~/.tmux/plugins/tpm/bin/clean_plugins	    # prefix + alt + u
~/.tmux/plugins/tpm/bin/install_plugins	    # prefix + I

# Update zsh

zgen selfupdate
zgen reset
zgen update
