#!/bin/bash

BIN_DIR="$HOME/bin/"

mkdir -p $BIN_DIR
export PATH=$BIN_DIR:$PATH

# Install dotfiles using bashdot

git submodule update --init --recursive
~/dotfiles/bashdot/bashdot install default

# Install dependencies

pip install --user black pylint pyenchant flake8 pyls isort

if [ $1 = "mac" ]; then
    # MacOS

    # Fix copy-paste in MacOS
    brew install reattach-to-user-namespace

    # Spell checker for pylint
    brew install enchant
else
    # Linux
fi

# Update tpm

~/.tmux/plugins/tpm/bin/update_plugins all	# prefix + U
~/.tmux/plugins/tpm/bin/clean_plugins	    # prefix + alt + u
~/.tmux/plugins/tpm/bin/install_plugins	    # prefix + I

# Update zsh

zgen selfupdate
zgen reset
zgen update
