function kiro-cli --description 'Wrapper: auto-trust the `subagent` tool in `kiro-cli chat` so subagent spawns are not re-approved every session. AIM-proof (the stores-builder agent config is regenerated by AIM and cannot hold this persistently). Delete this file to revert.'
    # Only augment the interactive `chat` subcommand; everything else passes straight through.
    if test (count $argv) -ge 1; and test "$argv[1]" = chat
        if string match -qr -- '^--trust' $argv
            # User already passed a trust flag (e.g. --trust-all-tools); don't double-inject.
            command kiro-cli $argv
        else
            command kiro-cli chat --trust-tools=subagent $argv[2..-1]
        end
    else
        command kiro-cli $argv
    end
end
