[general]
default_session_mode = "agent"

[agents]

[agents.third_party]
should_render_cli_agent_toolbar = true

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.other]
show_agent_notifications = true
show_conversation_history = false

[agents.execution_profiles]

[agents.execution_profiles.default]
apply_code_diffs = "always_ask"
ask_user_question = "always_ask"
autosync_plans_to_warp_drive = true
base_model = "auto-genius"
command_allowlist = []
command_denylist = [
  'bash(\s.*)?',
  'fish(\s.*)?',
  'pwsh(\s.*)?',
  'sh(\s.*)?',
  'zsh(\s.*)?',
  'curl(\s.*)?',
  'eval(\s.*)?',
  'exec(\s.*)?',
  'source(\s.*)?',
  'wget(\s.*)?',
  'dig(\s.*)?',
  'nslookup(\s.*)?',
  'host(\s.*)?',
  'ssh(\s.*)?',
  'scp(\s.*)?',
  'rsync(\s.*)?',
  'telnet(\s.*)?',
  'rm(\s.*)?',
]
computer_use = "never"
directory_allowlist = []
execute_commands = "agent_decides"
mcp_allowlist = []
mcp_denylist = []
mcp_permissions = "agent_decides"
name = "Default"
read_files = "always_allow"
run_agents = "always_ask"
web_search_enabled = true
write_to_pty = "always_ask"

[appearance]

[appearance.themes]
theme = "dracula"

[appearance.vertical_tabs]
enabled = false

[code]

[code.editor]
show_code_review_button = false
show_project_explorer = false
show_global_search = false

[warp_drive]
enabled = false
